package com.tier2.submitquotebind;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity(name = "submission")
@javax.persistence.Table(name = "submission", schema = "pam")
public class Submission implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Original Insured")
	private java.lang.String originalInsured;
	@org.kie.api.definition.type.Label("Sum Insured")
	private java.math.BigDecimal sumInsured;
	@org.kie.api.definition.type.Label("Premium")
	private java.math.BigDecimal premium;
	@org.kie.api.definition.type.Label("Quote Accepted?")
	private boolean quoteAccepted;
	@org.kie.api.definition.type.Label("Quote Bound?")
	private boolean quoteBound;

	@org.kie.api.definition.type.Label("Risk Class")
	private java.lang.String riskClass;

	@org.kie.api.definition.type.Label("Country of Insured")
	private java.lang.String insuredCountry;

	@org.kie.api.definition.type.Label("Inception Date")
	private java.util.Date inceptionDate;

	@org.kie.api.definition.type.Label("Period")
	private java.lang.Integer period;

	@org.kie.api.definition.type.Label("NTU?")
	private boolean ntu;

	@org.kie.api.definition.type.Label("Reason for NTU")
	private java.lang.String ntuReason;

	@org.kie.api.definition.type.Label("Additional Info Required?")
	private boolean requiresInfo;

	@org.kie.api.definition.type.Label("Additional Info")
	private java.lang.String additionalInfo;

	@javax.persistence.GeneratedValue(generator = "SUBMISSION_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "SUBMISSION_ID_GENERATOR", sequenceName = "SUBMISSION_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Auto Rejected")
	private boolean autoRejected;

	public Submission() {
	}

	public java.lang.String getOriginalInsured() {
		return this.originalInsured;
	}

	public void setOriginalInsured(java.lang.String originalInsured) {
		this.originalInsured = originalInsured;
	}

	public java.math.BigDecimal getSumInsured() {
		return this.sumInsured;
	}

	public void setSumInsured(java.math.BigDecimal sumInsured) {
		this.sumInsured = sumInsured;
	}

	public java.math.BigDecimal getPremium() {
		return this.premium;
	}

	public void setPremium(java.math.BigDecimal premium) {
		this.premium = premium;
	}

	public java.lang.String getRiskClass() {
		return this.riskClass;
	}

	public void setRiskClass(java.lang.String riskClass) {
		this.riskClass = riskClass;
	}

	public java.lang.String getInsuredCountry() {
		return this.insuredCountry;
	}

	public void setInsuredCountry(java.lang.String insuredCountry) {
		this.insuredCountry = insuredCountry;
	}

	public java.util.Date getInceptionDate() {
		return this.inceptionDate;
	}

	public void setInceptionDate(java.util.Date inceptionDate) {
		this.inceptionDate = inceptionDate;
	}

	public java.lang.Integer getPeriod() {
		return this.period;
	}

	public void setPeriod(java.lang.Integer period) {
		this.period = period;
	}

	public java.lang.String getNtuReason() {
		return this.ntuReason;
	}

	public void setNtuReason(java.lang.String ntuReason) {
		this.ntuReason = ntuReason;
	}

	public java.lang.String getAdditionalInfo() {
		return this.additionalInfo;
	}

	public void setAdditionalInfo(java.lang.String additionalInfo) {
		this.additionalInfo = additionalInfo;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public boolean isQuoteAccepted() {
		return this.quoteAccepted;
	}

	public void setQuoteAccepted(boolean quoteAccepted) {
		this.quoteAccepted = quoteAccepted;
	}

	public boolean isQuoteBound() {
		return this.quoteBound;
	}

	public void setQuoteBound(boolean quoteBound) {
		this.quoteBound = quoteBound;
	}

	public boolean isNtu() {
		return this.ntu;
	}

	public void setNtu(boolean ntu) {
		this.ntu = ntu;
	}

	public boolean isRequiresInfo() {
		return this.requiresInfo;
	}

	public void setRequiresInfo(boolean requiresInfo) {
		this.requiresInfo = requiresInfo;
	}

	public boolean isAutoRejected() {
		return this.autoRejected;
	}

	public void setAutoRejected(boolean autoRejected) {
		this.autoRejected = autoRejected;
	}

	public Submission(java.lang.String originalInsured,
			java.math.BigDecimal sumInsured, java.math.BigDecimal premium,
			boolean quoteAccepted, boolean quoteBound,
			java.lang.String riskClass, java.lang.String insuredCountry,
			java.util.Date inceptionDate, java.lang.Integer period,
			boolean ntu, java.lang.String ntuReason, boolean requiresInfo,
			java.lang.String additionalInfo, java.lang.Long id,
			boolean autoRejected) {
		this.originalInsured = originalInsured;
		this.sumInsured = sumInsured;
		this.premium = premium;
		this.quoteAccepted = quoteAccepted;
		this.quoteBound = quoteBound;
		this.riskClass = riskClass;
		this.insuredCountry = insuredCountry;
		this.inceptionDate = inceptionDate;
		this.period = period;
		this.ntu = ntu;
		this.ntuReason = ntuReason;
		this.requiresInfo = requiresInfo;
		this.additionalInfo = additionalInfo;
		this.id = id;
		this.autoRejected = autoRejected;
	}

}